# Generated by Django 5.1.4 on 2025-03-01 16:05

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('app_link', models.CharField(max_length=255, unique=True)),
                ('app_category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('points', models.PositiveIntegerField()),
                ('app_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
